---
test_mode: false
SERVER_SETTINGS:
  server_software: ${SERVER_SOFTWARE}
  mars_url: ${MARS_URL}
  SURVEY_SETTINGS:
    ztf:
      id: "ztf"
      bucket: ${ZTF_BUCKET_NAME}
    atlas:
      id: "atlas"
      bucket: ${ATLAS_BUCKET_NAME}
RALIDATOR_SETTINGS:
  SECRET_KEY: ${SECRET_KEY}
  ON_AUTH_ERROR_DEFAULT_USER: true